### ISSUE TITLE
شکل نقطه‌ها

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/shabnam-font#1]
شکل نقطه‌ها متناسب با بقیه حروف نیست
نقطه‌ها شبیه نقطه نستعلیق هستند

**Comment by rastikerdar** [comment]
حق با شماست. نقطه ها در نسخه 0.3.4 به دایره تبدیل شدند.

از شما سپاسگزارم برای این گزارش

**Comment by behdad222** [comment]
@rastikerdar خوب با مسیج کامیتت ایشو رو هم ببند :)
