### ISSUE TITLE
بهبود ف

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/shabnam-font#10]
فعلی:
![old-feh](https://cloud.githubusercontent.com/assets/3116038/11547871/87fc2bb8-996c-11e5-92c3-c5fafa57b396.png)

پیشنهادی:
![new-feh](https://cloud.githubusercontent.com/assets/3116038/11547873/89cacf30-996c-11e5-95d7-220dfac3f9e6.png)

**Comment by aziz** [comment]
:+1:
