### ISSUE TITLE
بزرگتر شدن سایز قلم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/shabnam-font#11]
در حال حاضر اندازه قلم با بی یکان بیشتر ست هست ولی فکر می کنم منطقیش هماهنگی با تاهوما و دروید هست تا با بیشتر با فونت های انگلیسی هماهنگ باشه. تقریبا مثل صمیم و وزیر و پرستو.

**Comment by aziz** [comment]
موافقم

**Comment by rastikerdar** [comment]
کل سایز فونت بزرگ شد. فکر می کنم بهترین حالت برای هماهنگی با لاتین شد. خیلی وحشتناک بود!

**Comment by rastikerdar** [comment]
ظاهرا یه کم زیادی بزرگ شده. فکر کنم یه ذره باید کوچکتر بشه. کم دقتی کردم.

**Comment by rastikerdar** [comment]
سایز رو باز یه ذره توی 0.7 کوچکتر کردم. الان هر چی نگاه می کنم بهتر از این حالتی به ذهنم نمیرسه.
