### ISSUE TITLE
اندازه شکل ط و ص

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/shabnam-font#12]
به نظر شما این فضای داخلی ط که اسمشو نمیدونم چیه یه کم زیادی بزرگ نیست؟
![tah](https://cloud.githubusercontent.com/assets/3116038/11833466/31623380-a3d8-11e5-93cf-7ec4c78bdea3.png)

**Comment by rastikerdar** [comment]
کرنینگ داد میزنه که مشکل داره! :)

**Comment by zoghal** [comment]
به فضای سفیدی داخل حروف چشم گفته می شود.
عرض حروف ص‍ و ط باید هم عرض سر ن باشه.

**Comment by rastikerdar** [comment]
ممنونم صالح.
سایزشو کوچکتر کردم.
