### ISSUE TITLE
باگ عجیب در اتصال میم به ث غیر چسبان

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#14]
<img width="57" alt="screen shot 2015-12-31 at 1 18 20 pm" src="https://cloud.githubusercontent.com/assets/3202/12064347/0618e3dc-afc1-11e5-9b26-1801c15e86e2.png">
به محض تبدیل ث به ث چسبان این مشگل حل می‌شه.
<img width="72" alt="screen shot 2015-12-31 at 1 18 31 pm" src="https://cloud.githubusercontent.com/assets/3202/12064348/07504830-afc1-11e5-8372-01eccf58bff5.png">
فقط هم برای ث این مشکل وجود داره
<img width="67" alt="screen shot 2015-12-31 at 1 19 45 pm" src="https://cloud.githubusercontent.com/assets/3202/12064355/30142fca-afc1-11e5-97b7-a20d6c600898.png">

**Comment by rastikerdar** [comment]
باگ مربوط به خود ـث هست. وقتی اندازه ها تغییر رو میدم بعضا اتفاقات عجیبی رخ میده.
RBearing توی ـث خیلی کم شده

**Comment by rastikerdar** [comment]
تصحیح شد.
با تشکر از شما
