### ISSUE TITLE
بلندتر کردن دندانه‌ها

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#15]
به نظرم اگر دندانه‌ها کمی بلند‌تر شوند شخصیت بهتری به قلم می‌دهند.
به عنوان نمونه:
<img width="128" alt="screen shot 2015-12-31 at 1 10 45 pm" src="https://cloud.githubusercontent.com/assets/3202/12064413/fbdf22c6-afc2-11e5-929d-bd98cf1ebd2e.png">
<img width="128" alt="sample" src="https://cloud.githubusercontent.com/assets/3202/12064414/fde86b22-afc2-11e5-91fa-5b2176f4450c.png">

**Comment by rastikerdar** [comment]
به نظرتون بلندتر بشه فونت خشن نمیشه؟
الان این شکلی هست
![screenshot from 2016-01-01 02-20-49](https://cloud.githubusercontent.com/assets/3116038/12068925/6848f840-b02e-11e5-9259-330d81e29ce1.png)

**Comment by aziz** [comment]
مقدار بلندشدن باید کم باشه. این دو تا رو مقایسه کنید
<img width="96" alt="shabnam" src="https://cloud.githubusercontent.com/assets/3202/12069993/f42f604a-b058-11e5-843f-44c34ea3ea8a.png">

**Comment by rastikerdar** [comment]
همه دندانه ها بلندتر شد
![screenshot from 2016-01-03 09-58-19](https://cloud.githubusercontent.com/assets/3116038/12077770/3aa25f8e-b20a-11e5-9594-aabc83d8e2e9.png)

متشکرم
