### ISSUE TITLE
نازک شدن اتصال به میم از راست

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#16]
قلم مونو استروک قراره باشه
<img width="443" alt="ghalam" src="https://cloud.githubusercontent.com/assets/3202/12065468/2f7ef510-afd8-11e5-9721-56efd3172763.png">

**Comment by rastikerdar** [comment]
یه کم بهترش کردم. البته فکر کنم کامل نشد
![screenshot from 2016-01-01 01-50-40](https://cloud.githubusercontent.com/assets/3116038/12068771/2a5388f6-b02a-11e5-8f53-094a618af2d5.png)

**Comment by aziz** [comment]
بهتر شده خسته نباشی
