### ISSUE TITLE
انتهای استروک ه چسبان آخر صحیح نیست

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#17]
<img width="643" alt="ezafeh" src="https://cloud.githubusercontent.com/assets/3202/12065480/70081990-afd8-11e5-8178-bf42e13373a0.png">

**Comment by rastikerdar** [comment]
نمی دونم بهتر شد یا نه؟
![screenshot from 2016-01-01 01-48-52](https://cloud.githubusercontent.com/assets/3116038/12068757/e541f414-b029-11e5-8683-c5e0fd66abae.png)

**Comment by aziz** [comment]
:+1:
