### ISSUE TITLE
طرح جدید برای گلیف‌های ح، ج، چ و خ

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#18]
این جیم خیلی ضایع است. به نظرم اینجا رو باید از یکان وام گرفت
<img width="568" alt="screen shot 2015-12-31 at 3 53 31 pm" src="https://cloud.githubusercontent.com/assets/3202/12065494/ac415836-afd8-11e5-96ce-2de354a530c7.png">

**Comment by rastikerdar** [comment]
آهان کلا این شکلو رو نمی پسندین. حقیقتش اولین گلیفی که توی شبنم طراحی کردم همین حـ بود.
حالا یکی دو تا طراحی جدید می ذارم شاید بپسندین.

**Comment by rastikerdar** [comment]
توی نسخه جدید اینجوریش کردم
![screenshot from 2016-03-19 21-25-55](https://cloud.githubusercontent.com/assets/3116038/13900332/4479a418-ee19-11e5-989d-a75cd53a0408.png)

اگر خوب نیست یه شکل دیگه در بیارم

راستی عزیز جان. برای راست به چپ فکر کنم همین یه عبارت توی کد اچ تی ام ال کفایت کنه:
`dir="auto"`
هم توی ادیتور و هم توی کامنت ها. اینجوری دیگه نیازی هم نیست آپشنی براش بزران یا کدی توی منطق برنامشون بنویسن.

**Comment by zoghal** [comment]
خیلی بهتر شده :+1:

**Comment by rastikerdar** [comment]
![screenshot from 2016-03-24 12-01-27](https://cloud.githubusercontent.com/assets/3116038/14011002/5462f0b2-f1b8-11e5-99e6-b3ba1fe04496.png)

![screenshot from 2016-03-24 12-01-40](https://cloud.githubusercontent.com/assets/3116038/14011005/596b98a2-f1b8-11e5-8b30-09b1c4da7125.png)

**Comment by aziz** [comment]
از قبل خیلی بهتر شده. من شبنم رو به گیت‌هاب و بی‌بی‌سی اضافه کردم هر روز دارم ازش استفاده می‌کنم به نظرم خیلی بهتر شده نسبت به روزهای اول. برای طراحی رابط‌های کاربر خیلی مناسبه.

**Comment by rastikerdar** [comment]
خوشحالم پسندیدین
پس با اجازه ایشو رو میبندم ولی اگه شکل بهتری دیدم دوباره باز می کنم.
بابت ایشو متشکرم
