### ISSUE TITLE
تراز سر ی با شکمش

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#19]
مقایسه کنید. دومی پیشنهاد منه. 
<img width="308" alt="screen shot 2015-12-31 at 3 53 26 pm" src="https://cloud.githubusercontent.com/assets/3202/12065506/f4460ffa-afd8-11e5-8720-242e4950b4b4.png">
<img width="308" alt="ey" src="https://cloud.githubusercontent.com/assets/3202/12065508/f684cc16-afd8-11e5-8ee0-803418cf26f5.png">

**Comment by aziz** [comment]
البته من هنوز این گرد شدگی ابتدا و انتهای استروگ ی رو درک نمی‌کنم. به نظرم اگر انتهای همه استروک‌ها تیز باشه بهتر دیده می‌شه. البته این دیگه اشکال نیست و سلیقه است

**Comment by rastikerdar** [comment]
.درسته همشو صاف می کنم

**Comment by rastikerdar** [comment]
توی ۰.۷ همه رو صاف کردم
![screenshot from 2016-01-01 01-47-04](https://cloud.githubusercontent.com/assets/3116038/12068745/9d388f20-b029-11e5-88ef-64a11b64e9c4.png)

**Comment by aziz** [comment]
اصل موضوع این ایشو حل نشد و بسته شد! 
منظورم تراز سر یا با شکمش در سمت راست بود. تو شکل دقت کن

**Comment by rastikerdar** [comment]
اوه عزیز جان اصلا متوجه نشدم. ببخشید.
اصلاحش کردم

ممنون
