### ISSUE TITLE
اندازه نقاط

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#2]
به نظر نقاط باید کمی بزرگتر باشه. مشابه یکان

<img width="231" alt="screen shot 2015-12-02 at 4 25 22 am" src="https://cloud.githubusercontent.com/assets/3202/11521477/d1f272a6-98ac-11e5-9eb5-a006bf8855e6.png">
<img width="240" alt="screen shot 2015-12-02 at 4 25 46 am" src="https://cloud.githubusercontent.com/assets/3202/11521479/d595d4b6-98ac-11e5-93ba-e1fd44f84764.png">

**Comment by rastikerdar** [comment]
فقط یه نکته کوچولو قبل از پرداختن کامل به این قلم عرض کنم هر چند ممکنه آن رویه هم بنا به نظر جمع عوض بشه:
در آغاز پروژه به هیچ وجه قرار نبود این فونت یکان آزاد شود. بنا بر این بود که فونتی جدید با نسبت ها و شکلی که به نظر می آمد بهتر است پدید آید. از این رو پیشنهاد می کنم زیاد مقایسه نفرمایید و آن چیزی که به نظرتان بهتر است بیان نمایید.
البته باز هم عرض می کنم این فقط یه پیشنهاد بود.

**Comment by zoghal** [comment]
موافقم منم بهتره زیاد به یکان نزدیک نشه.  چند نمونه تایپ فیس نمونه میزارم تا بتونید از اونها ایده بگیرید.
![benobagheri--beno-2011](https://cloud.githubusercontent.com/assets/174688/11833294/70d8a884-a3d6-11e5-8328-786dd2ab92f2.jpg)
![27ed3b28322559838943317f46bbb16f](https://cloud.githubusercontent.com/assets/174688/11833298/7795265c-a3d6-11e5-8bb6-0b53374dce09.jpg)
![edd487dc294310185eeb804cc900e458](https://cloud.githubusercontent.com/assets/174688/11833301/7b727fe0-a3d6-11e5-847f-6fd34e21528d.jpg)
![fa8c56415d43373323cd0c6cfc96c05e](https://cloud.githubusercontent.com/assets/174688/11833304/842002c0-a3d6-11e5-963d-77887e07cac5.jpg)

**Comment by zoghal** [comment]
![031a3cce998f6dacb1f2b277ddfe7068](https://cloud.githubusercontent.com/assets/174688/11833319/9da3ac1a-a3d6-11e5-8798-c32e3cf822d9.jpg)
![fc9824766ff0ceb4ba078d5baabacfbc](https://cloud.githubusercontent.com/assets/174688/11833322/9ef96000-a3d6-11e5-9384-0f18f138219a.jpg)

**Comment by rastikerdar** [comment]
اندازه نقطه ها توی تصویر آخری رو خیلی دوست دارم. خیلی به تایپ فیسش میاد.

**Comment by zoghal** [comment]
نقطه مهمترین بخش خوشنویسی هست. واحد اندازه گیری و ... در خوشنویسی همین نقطه هست. 
![bm3jrqhccaagek4 jpg large](https://cloud.githubusercontent.com/assets/174688/11841674/2010d69a-a414-11e5-8232-72beec008112.jpg)
![bm3koe6ciaang72 jpg large](https://cloud.githubusercontent.com/assets/174688/11841672/1f137676-a414-11e5-8f6d-2fde88fa9375.jpg)
![bm80cuyccaehy8j jpg large](https://cloud.githubusercontent.com/assets/174688/11841667/1e4684c2-a414-11e5-9137-bea302508fd7.jpg)
![bm80iq_ceaekph- jpg large](https://cloud.githubusercontent.com/assets/174688/11841668/1e532c5e-a414-11e5-866b-9ec481e0f81f.jpg)
![bmyeco2cyaazwnm jpg large](https://cloud.githubusercontent.com/assets/174688/11841669/1e55315c-a414-11e5-8c2d-acd1e5937849.jpg)
![bmyfzincmaiaopt jpg large](https://cloud.githubusercontent.com/assets/174688/11841670/1e59291a-a414-11e5-9567-d361cd85e631.jpg)
![bncrbdnciail66s jpg large](https://cloud.githubusercontent.com/assets/174688/11841671/1e832846-a414-11e5-8a02-403db6278ac6.jpg)
-----------------
اگر درج تصویر اذیت میکنه لطفا بگید. من هدفم راهنمایی به صورت تصویری هست.

**Comment by rastikerdar** [comment]
من که به شخصه از خدامه شما این جور ایشوها رو بذارید. این تصاویر در مورد نقطه خوشنویسی خیلی جالب بود.

**Comment by rastikerdar** [comment]
![screenshot from 2016-01-01 02-15-32](https://cloud.githubusercontent.com/assets/3116038/12068888/9ba1420c-b02d-11e5-84da-00e814cd9691.png)

**Comment by zoghal** [comment]
:+1: در مورد این موارد تا دلت بخواد هم تصویر هست . هم اسکچ بگو تا آپلود کنم.
