### ISSUE TITLE
تغییر قطر استروک در صاد و ضاد

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#20]
اینجا باز داره یه اتفاقات عجیب و غریبی برای قطر استروک میوفته و استروک‌ها قاطی پاتی میشن!
<img width="643" alt="ezafe2" src="https://cloud.githubusercontent.com/assets/3202/12065550/930eb484-afd9-11e5-9ec8-0538da8ac8e7.png">

**Comment by rastikerdar** [comment]
تو نسخه ۰.۷ این شکلی شد

![screenshot from 2016-01-01 01-44-48](https://cloud.githubusercontent.com/assets/3116038/12068736/4f7a39e6-b029-11e5-8dde-c8e75aec104b.png)

**Comment by aziz** [comment]
بهتر شده مرسی. ولی هنوز هم یک نازک‌‌شدگی مختصری در محل اتصال چشم صاد به دندانه دیده می‌شه.

**Comment by rastikerdar** [comment]
شکل صاد در نسخه جدید تغییر کرده:
![screenshot from 2016-03-24 21-33-28](https://cloud.githubusercontent.com/assets/3116038/14024703/1fb177e4-f208-11e5-8cf9-8c1a24739aff.png)

اگر می پسندین یا اشکالی نمیبینید که ایشو رو ببندیم؟
بابت ایشو هم ممنونم
