### ISSUE TITLE
عدم تناسب ف و ق وسط با سایز اشکال این حروف

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#21]
قاف چسبان از هر دو سمت کمی بزرگتر به نظر میاد
<img width="130" alt="screen shot 2016-01-01 at 1 23 54 am" src="https://cloud.githubusercontent.com/assets/3202/12070001/73c24958-b059-11e5-9fee-e554f75a81c2.png">

**Comment by rastikerdar** [comment]
یه مقدار کوچکترش کردم
![screenshot from 2016-01-03 09-33-24](https://cloud.githubusercontent.com/assets/3116038/12077751/7aa94530-b209-11e5-8401-a55a385293ff.png)

**Comment by rastikerdar** [comment]
اینو تا شهیدش نکردی فکر می کنم هنوز جای کار داره :D

**Comment by aziz** [comment]
آره موافقم. گردن ف و قاف اول کلمه کنی بلنده

**Comment by rastikerdar** [comment]
البته توی نسخه اخیر این شکلی شده
![screenshot from 2016-03-24 22-00-58](https://cloud.githubusercontent.com/assets/3116038/14025481/f105761c-f20b-11e5-9da3-dc6e164c1bdf.png)

فکر می کنم مشکل ـقـ حل شده اما متاسفانه نقطه هاش زیادی بالاست

قـ ابتدا موافقم زیادی بلنده البته تو گرافیک پایین اگر پایین تر باشه میچسبه و سیاه میشه.
هر چند که الان اینطوریه:
![screenshot from 2016-03-24 22-04-36](https://cloud.githubusercontent.com/assets/3116038/14025601/8a83efe4-f20c-11e5-9e04-aeeff3ded545.png)

![screenshot from 2016-03-24 22-06-32](https://cloud.githubusercontent.com/assets/3116038/14025651/c1cf883c-f20c-11e5-8c91-e9ef8ff51982.png)

**Comment by zoghal** [comment]
قامت قاف و ف فرم اول از اول درست بود
