### ISSUE TITLE
اعداد فارسی

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#22]
اعداد اصلا به این قلم نمیان. به نظرم بهتره کمی صاف و صوف تر باشند. 
<img width="551" alt="screen shot 2016-01-01 at 1 39 08 am" src="https://cloud.githubusercontent.com/assets/3202/12070009/36ed27cc-b05a-11e5-9795-770eefc7b73e.png">

یکان برای مقایسه
<img width="461" alt="screen shot 2016-01-01 at 1 39 02 am" src="https://cloud.githubusercontent.com/assets/3202/12070010/45b6ac06-b05a-11e5-9e14-c6c5f816054a.png">

کرنینگ اعداد هم داغونه
<img width="30" alt="screen shot 2016-01-01 at 1 35 21 am" src="https://cloud.githubusercontent.com/assets/3202/12070011/4f06fdba-b05a-11e5-9c39-f0c560f5d2b2.png">
<img width="110" alt="screen shot 2016-01-01 at 1 42 11 am" src="https://cloud.githubusercontent.com/assets/3202/12070012/577911d6-b05a-11e5-883e-4494f5eda72e.png">

**Comment by rastikerdar** [comment]
اینم توی نسخه 0.7.2
هم شکل هم اندازه تغییر کرد
![screenshot from 2016-01-03 09-16-30](https://cloud.githubusercontent.com/assets/3116038/12077754/9e79b79c-b209-11e5-9d47-c6e0d9cf47b6.png)
![screenshot from 2016-01-03 09-23-38](https://cloud.githubusercontent.com/assets/3116038/12077757/b5df68d2-b209-11e5-983f-b1ff602ede47.png)

اینکه کرنینگ نداشت به دلیل این بود که اندازه عرض گلیف اعداد یکی بود. اینطوری وقتی زیر هم قرار می گرفتن عقب جلو نمی شدند. توی فونت دژاوو هم یکی هست. اما خب از نقظه نظر زیبایی زشت میشه.

به هر صورت من برای شما متغیرش کردم.

**Comment by rastikerdar** [comment]
عزیز جان اگه شکل اعداد رو می پسندی که پروندشو ببندیم؟ اگه ایرادی میبینی حتما بفرما تا رفعش کنم.

**Comment by aziz** [comment]
به نظرم خوب شده. ببند
