### ISSUE TITLE
کرنینگ

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#23]
کرنینگ را با دال
<img width="33" alt="screen shot 2016-01-01 at 1 54 51 am" src="https://cloud.githubusercontent.com/assets/3202/12070014/911d8412-b05a-11e5-9183-448c07de3661.png">
کرنینگ را با لام
<img width="42" alt="screen shot 2016-01-01 at 1 52 40 am" src="https://cloud.githubusercontent.com/assets/3202/12070015/94815a52-b05a-11e5-8de7-baf13e20cf8d.png">

**Comment by rastikerdar** [comment]
در نسخه 0.7.2 اصلاح شد.
متشکرم عزیز
