### ISSUE TITLE
همزه

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#24]
همزه کرسی که اصلا تو یه فاز دیگه است

<img width="102" alt="screen shot 2016-01-01 at 1 58 58 am" src="https://cloud.githubusercontent.com/assets/3202/12070018/b585e72c-b05a-11e5-9f2e-4f62301cfb6e.png">

همزه روی یا هم وزنش خیلی کمتر خود قلمه
<img width="73" alt="screen shot 2016-01-01 at 1 44 32 am" src="https://cloud.githubusercontent.com/assets/3202/12070022/bb8e9952-b05a-11e5-80cf-6d4562b05aa1.png">

**Comment by rastikerdar** [comment]
اصلاح گردید:
![screenshot from 2016-01-03 10-27-05](https://cloud.githubusercontent.com/assets/3116038/12077778/876d63f4-b20a-11e5-99cb-0b408af9686d.png)
![screenshot from 2016-01-03 10-30-36](https://cloud.githubusercontent.com/assets/3116038/12077780/913ff676-b20a-11e5-8ccb-0a0acfa7772b.png)
![screenshot from 2016-01-03 11-11-21](https://cloud.githubusercontent.com/assets/3116038/12077784/cb828d4e-b20a-11e5-8e19-e7adb615c950.png)

اگر باز هم مشکلی بود ایشو رو باز کنید.
متشکرم
