### ISSUE TITLE
مشکل کاراکتر جداکننده هزارگان

### ISSUE THREAD

**Issue by MohMah** [rastikerdar/shabnam-font#26]
سلام، ممنون ازین فونت زیبا؛ کاراکتر جداکننده هزارگان به شکل زیر به نمایش درمیاد که مشکل داره:
![photo_2016-03-12_20-17-52](https://cloud.githubusercontent.com/assets/1501834/13724096/b14f397a-e88f-11e5-99ca-ea8a01de4820.jpg)

**Comment by rastikerdar** [comment]
متشکرم برای گزراش این اشکال. کاملا درست می فرمایید. در نسخه جدید تصحیح می گردد.

**Comment by rastikerdar** [comment]
در نسخه جدید 0.8.1 این مشکل رفع گردید. در صورت مشاهده هر گونه ایرادی در فونت ممنونم میشم باز هم گزارش بدین.

با تشکر

**Comment by MohMah** [comment]
خیلی ممنون
