### ISSUE TITLE
مشکل ویرگول به وسیله کیبورد استاندارد مکینتاش

### ISSUE THREAD

**Issue by mimalef70** [rastikerdar/shabnam-font#27]
![font-shabnam](https://cloud.githubusercontent.com/assets/17767869/13774077/3252a9fc-eab2-11e5-986d-33f8cc973fdf.jpg)

سلام. 

ممنون بابت این فونت زیبا. من به یک مشکلی خوردم٬ وقتی کاراکتر ویرگول رو درسایتم استفاده میکنم درست چاپ نمیشه. 
با کپی پیست کردن بعضی ویرگول های سایت های دیگه این مشکل حل میشه . 
من با کیبورد Persian - ISIR این تست رو انجام دادم

با تشکر

**Comment by aziz** [comment]
من این مشکل ندارم. 
از کیبورد Persian - ISIRI هم استفاده میکنم.
Shift+7 کلید ویرگوله

**Comment by zoghal** [comment]
در صورتی که مجدد مشکل داشتید یک بار تو این آدرس 
http://r12a.github.io/apps/conversion/
و تو باکس اول بین دو کلمه ویرگول وارد کنید و کد تبدیل شده رو بدید تا متوجه بشیم شما دقیقا چه کلیدی را فشار میدید و داستان چی هست.

**Comment by rastikerdar** [comment]
آیا همچنان مشکل پابرجاست؟.

**Comment by mimalef70** [comment]
من معذرت میخوام ایشو رو سرپا نگه داشتم، در سفر به سر میبردم. 
ممنون از aziz 
مشکل این بود که من شیفت ۲ رو استفاده میکردم که کاراکتر اشتباهی بود. 

متشکر از زحمتاتون

**Comment by rastikerdar** [comment]
البته اون موردی که استفاده می کردید رو هم در نسخه جدید اصلاح کردم. اون شکل متاسفانه دست نخورده باقی مونده بود.
