### ISSUE TITLE
به هم ریختن فاصله بین حروف یک کلمه

### ISSUE THREAD

**Issue by MasoodFallahpoor** [rastikerdar/shabnam-font#28]
وقتی متنی انگلیسی و یا متنی فارسی که شامل کلمات انگلیسی هم هست رو تو مایکروسافت ورد تایپ می‌کنم (با قلمی به جز شبنم) و بعد قلم کل متن رو به شبنم تغییر میدم حروف کلمات انگلیسی روی هم می‌افتن و یا بیش از حد از هم فاصله میگیرن و کاملا ناخوانا میشن. مطمئن نیستم که آیا مشکل از قلم شبنم هستش یا مایکروسافت ورد

Windows 8.1 64bit
Microsoft Word 2013 64bit
shabnam 0.9.1

**Comment by zoghal** [comment]
در این محصول و شاید خیلی های دیگر امکان تعریف دو فونت وجود دارد که اصطلاحات فونت مکمل می‌خوانیمشون
شما برای رفع این مشکل باید مطابق تصویر فونت‌ انگلیسی  و فارسی را تعریف کنید.
![s](https://www.dropbox.com/s/u5b9daku2wgvl4n/Screenshot%202016-04-03%2012.54.06.png?dl=0)

**Comment by rastikerdar** [comment]
حروف لاتین به قلم اضافه شد. فکر می کنم مشکل حل شده باشه. متشکرم برای گزارش این ایشو.
اگر مشکلی بود ایشو را مجددا باز بفرمایید.
