### ISSUE TITLE
افزودن CDN به فونت

### ISSUE THREAD

**Issue by sIiiS** [rastikerdar/shabnam-font#29]
خیلی خیلی ممنون از زحمات شما دوست عزیز
اگر امکان داره شبیه به فونت وزیر برای این فونت هم از RawGit استفاده کنید

**Comment by rastikerdar** [comment]
به روی چشم. در نسخه آتی همین گونه خواهد شد.

**Comment by rastikerdar** [comment]
این امکان اضافه شد. متشکرم
