### ISSUE TITLE
همسان سازی اندازه تمام دندانه‌ها

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#3]
در یکان همه دندانه‌های یک اندازه‌اند که برای قلمی به این سبک مناسب‌تره

![screen shot 2015-12-02 at 2 21 18 am copy](https://cloud.githubusercontent.com/assets/3202/11521559/a21269f0-98ad-11e5-9920-f8ef6c2b1227.png)
<img width="893" alt="screen shot 2015-12-02 at 4 53 09 am" src="https://cloud.githubusercontent.com/assets/3202/11521827/a2dbe4b2-98b0-11e5-9a62-598013dc5293.png">

**Comment by rastikerdar** [comment]
![screenshot from 2016-01-03 10-14-59](https://cloud.githubusercontent.com/assets/3116038/12077744/fefe1884-b208-11e5-9537-f31d8f2c4153.png)

اصلاح شد. فقط دندونه شروع رو یه کم فقط بلندتر گرفتم چون توی نمایش های کوچکتر پایین تر دیده یا شاید حس میشه.

**Comment by aziz** [comment]
عالیه
