### ISSUE TITLE
نمایش اعداد

### ISSUE THREAD

**Issue by salarcode** [rastikerdar/shabnam-font#30]
به نظر من اعداد خیلی داخل هم نمایش داده می شوند.
و خط تیره هم طول کافی رو نداره 
نمونه تصویر مقایسه با فونت BYekan
![image](https://cloud.githubusercontent.com/assets/1272095/20360721/11f93eaa-ac4a-11e6-81b7-7c619202eb30.png)

**Comment by rastikerdar** [comment]
حق با شماست. در کاهش فاصله زیاده روی شده است.
متشکرم برای گزارش این اشکال.

**Comment by dehghani-mehdi** [comment]
سلام،

سپاس بابت مجموعه فونت ها، مخصوصا این فونت، خیلی فونت خوبیه.
فک میکنم که با اصلاح اعداد فارسی، اعداد انگلیسی هم اصلاح بشن (تخصصی در مورد طراحی فونت ندارم)، فقط خواستم بگم که اعداد انگلیسی هم وضعیت مشابه ای دارند.

موفق یاشید.

**Comment by rastikerdar** [comment]
فاصله ارقام در نسخه جدید بیشتر شد.
با تشکر

سلام آقا مهدی
حقیقتش حروف انگلیسی بدون تغییر در فونت ادغام شده‌اند. یعنی فونت روبوتو اساسا بدین گونه هست. اگر این مورد مشکل ساز شده بهتره از نسخه بدون حروف انگلیسی استفاده کنید تا در انتخاب فونت انگلیسی دلخواهتون مخیر باشید. 
البته اینکه لزوما حروف لاتین بدون تغییر بمانند یا خیر در موردش هنوز صحبتی نشده.
