### ISSUE TITLE
bower installation problem.

### ISSUE THREAD

**Issue by ramajd** [rastikerdar/shabnam-font#32]
package installed using bower is not complete. it needs a css file to import.

**Comment by rastikerdar** [comment]
متشکرم برای گزارش این ایراد.
در نسخه جدید فایل باور رو اضافه کردم. امیدوارم مشکل رفع بشه.

**Comment by ramajd** [comment]
مشکل اینجاست که آخرین نسخه ای که در باور وجود داره ورژن 0.9.3 هستش در حالی که تو  گیتهاب تا نسخه 1.1.0 هم منتشر شده.
