### ISSUE TITLE
عدم پشتیبانی از خط تیره و اسلش

### ISSUE THREAD

**Issue by mahdimortazavi** [rastikerdar/shabnam-font#34]
باسلام فونت شبنم از خط تیره و اسلش پشتیبانی نمیکنه

**Comment by rastikerdar** [comment]
با سلام و احترام
از نسخه اصلی که با لاتین ترکیب شده استفاده کنید. نسخه بدون حروف لاتین فاقد برخی علائم نگارشی‌اند.

**Comment by mahdimortazavi** [comment]
متشکرم. پشتیبانی عالی بود
