### ISSUE TITLE
نبود فرمت  SVG

### ISSUE THREAD

**Issue by hoceyn** [rastikerdar/shabnam-font#36]
سلام. مرسی از فونت های زیبات. مرورگر پیش فرض اندروید 4.4  به پایین فقط از فونت  SVG فارسی پشتیبانی می کنه. بعد از تبدیل اتوماتیک این فونت به svg به تعداد زیادی از حروف غیر قابل نمایش می شن.

**Comment by rastikerdar** [comment]
سلام. ممنونم برای این ایشو. تلاش می‌کنم راهی برایش پیدا کنم.

**Comment by zoghal** [comment]
:)) این مشکل نوستولوژی بود واسه من، من رو برد به ۵ سال پیش که کلی مشکل فونت داشتیم.
در ابتدا دعوت می‌کنم این سه بحث رو مطالعه کنید، سالار یکسری مقدم در مورد مشکلات توضیح داده در وبلاگش:[[اینجا](https://sallar.me/farsi/persian-webfonts-display-issue-in-chrome-and-a-solution/) - [اینجا](https://sallar.me/farsi/web-typography-part-one/) - [اینجا](https://sallar.me/farsi/please-save-the-persian-script/)]

حالا چندتا نکته جهت استفاده از فرمت اس وی جی برای فونت فارسی:
۱- فرمت svg به هیچ عنوان از قابلیت‌های اوپن سورس پشتیبانی نمی‌کند، برای همین امکان نمایش صحیح متن فارسی را ندارند.مثلا حروف جدا جدا و بصورت مفردات نمایش داده میشوند «ب ت چ ج ».
۲- برای استفاده از فرمت اس وی جی باید روی متون یک عملیات ریشیپ انجام بگیرد. یعنی بسته به اینکه حرف ب در کجای کلمه قرار می‌گیره کد ینیکد حرف ب رو به یکی از ۴ حالات راست وصل، چپ وصل، دو سمت وصل و مفرد تبدیل شوند (ب‍ ‍ب‍ ‍ب ب) 
برای تست می تونید از این پروژه کمک بگیرید: [persian-reshaper](https://github.com/font-store/persian-reshaper)
در باکس بالا متن رو وارد کنید و در باکس پایین ریشیپ شده متن رو تحویل بگیرید.

اگر در این مورد سوالی هست من در خدمتم :) اما کلا پیشنهاد می‌کنم بیخیال بشید اون نسخه رو راحت ترید:)

**Comment by rastikerdar** [comment]
خدا خیرت بده آقای سوزنچی.
حسین آقا رضایت بده بیخیالش بشیم :)

**Comment by hoceyn** [comment]
خخخ اختیار پروژه دست شماست استاد. تا همین جاش هم کلی زحمت کشیدید . از طرف وب سازا و وب نویسا ممنونم از شما.
