### ISSUE TITLE
نکاتی در مورد تایپ فیس فونت شبنم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/shabnam-font#37]
این ایشو بازنشر نظر یکی از دوستان با نام "دوستان" در وبلاگ می‌باشد:
[لینک نظر](http://rastikerdar.blog.ir/1394/08/19/%D9%82%D9%84%D9%85-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%B4%D8%A8%D9%86%D9%85#comment-n8bwCa1NkW4)

>درود بر شما؛ خدا قوت
طی مشورت اینجانب با دوستان اهل فن و بازخوردهای مخاطبان چنانچه در تایپ‌فیس شبنم تغییراتی کوچک اما موثر اعمال شود استقلال بیشتری خواهد یافت و اشکالات -تکراری و ناچیز- قلم یکان را هم به دوش نمی‌کشد؛
-نقاط به شکل مربع با گوشه‌های مدور طراحی شوند و اندازه نقاط با تغییر وزن تغییری نامحسوس کند
-عمودی‌تر شدن حرف "ـه"
-حرف "ـهـ" از حالت فعلی به دو شکل گوشه دارتر یکسان با گوشه‌های مدور تغییر شکل یابد
-پایه حروف "ف" و "ق" کوتاه‌تر شود
-سرکج حروف کشیده‌تر، با کرسی خم‌تر طراحی شود
-تیزتر شدن گوشه‌های حروف در عین نرمی
پ.ن: این بررسی با در نظر گرفتن پارامترهای زیادی بدست آمده است.
با آرزوی موفقیت و سلامتی برای شما 

با تشکر از ایشان

**Comment by zoghal** [comment]
-عمودی‌تر شدن حرف "ـه" 👍 

>  -حرف "ـهـ" از حالت فعلی به دو شکل گوشه دارتر یکسان با گوشه‌های مدور تغییر شکل یابد:

حلقه پایین رو کوچیکتر بگیری هم بد نمیشه. فکر میکنم اگر حلقه‌ها یکسان نباشند بهتر جلوه میکنه

>  -پایه حروف "ف" و "ق" کوتاه‌تر شود 

: 👍  در ورن  لایت موفقم

**Comment by rastikerdar** [comment]
در نسخه جدید موارد فوق اعمال گردید. همچنین نکته‌ای که صالح عزیز فرمودند در مورد کوچکتر شدن حلقه پایینی ـهـ وسط.
با تشکر از دوستان
