### ISSUE TITLE
علائم نگارشی از فرم قلم پیروی نمی‌کنند

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#4]
![screen shot 2015-12-02 at 2 25 17 am](https://cloud.githubusercontent.com/assets/3202/11521619/41c925d8-98ae-11e5-8a73-4e768952b9fc.png)
![screen shot 2015-12-02 at 2 22 17 am](https://cloud.githubusercontent.com/assets/3202/11521622/46c7c878-98ae-11e5-8b9f-86ae77a0370c.png)

**Comment by rastikerdar** [comment]
این چطوره؟
![signs](https://cloud.githubusercontent.com/assets/3116038/11547029/33d1ac76-9966-11e5-92cd-e9d85ab4d796.png)

**Comment by msm1365** [comment]
دایره بهتره

**Comment by rastikerdar** [comment]
در حال حاضر این شکلی شده.
![screenshot from 2016-01-01 02-02-43](https://cloud.githubusercontent.com/assets/3116038/12068828/cf60fd82-b02b-11e5-9dac-ec7c3495ce44.png)

اگر خوب نیست ایشو رو مجددا باز کنید.
