### ISSUE TITLE
woff2

### ISSUE THREAD

**Issue by VSG24** [rastikerdar/shabnam-font#40]
<div dir=rtl>
پشتیبانی اکثر مرورگرها از فرمت woff2 به حدی رسیده که به نظرم وقتشه جایگزین woff بشه.
در حال حاضر خروجی woff2 برای این فونت وجود نداره.
</div>

**Comment by rastikerdar** [comment]
در نسخه جدید اضافه گردید. با تشکر از شما

**Comment by VSG24** [comment]
<div dir=rtl>مرسی و اما فایل font-face.css هم باید آپدیت بشه.</div>

**Comment by rastikerdar** [comment]
اضافه کردم. باز هم ممنون. اگر مشکلی بود بفرمایید تا رفع بشه.
