### ISSUE TITLE
Version 2.1.1 is being installed as the latest version.

### ISSUE THREAD

**Issue by mehrdadrafiee** [rastikerdar/shabnam-font#44]
Hey there,

Thanks for creating such a cool Persian font!

I just installed the package using [yarn](https://yarnpkg.com/en/), but version 2.1.1 was installed as the latest version not the 3.0.0. I see that the npm badge has v2.1.1, can this be updated to the latest version?

**Comment by rastikerdar** [comment]
Thank you Mehrdad!
I think we should ask the owner of the NPM repo @mberneti to help us.

**Comment by mehrdadrafiee** [comment]
Yeah. I create a yarn package last night but then realized that I don't have the permission to publish it 😄

**Comment by mberneti** [comment]
@rastikerdar , @mehrdadrafiee  the latest version (v3.0.0) released on NPM.

**Comment by mehrdadrafiee** [comment]
Cool! Thanks. I'll update the README and send a PR.

**Comment by mehrdadrafiee** [comment]
closing this since [it's been resolved](https://github.com/rastikerdar/shabnam-font/issues/44#issuecomment-381889833).
Thank you!
