### ISSUE TITLE
قطر استروک‌ها باید در تمام اجزای گلیف‌ها یکسان باشد

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#5]
بیشتر گلیف‌ها باید از این نظر بازنگری شوند
![screen shot 2015-12-02 at 2 22 24 am](https://cloud.githubusercontent.com/assets/3202/11521674/d98b76e6-98ae-11e5-8f17-1e095daa7b71.png)
![screen shot 2015-12-02 at 2 23 59 am](https://cloud.githubusercontent.com/assets/3202/11521682/ebf42de6-98ae-11e5-929d-c7b4baeb674e.png)

**Comment by rastikerdar** [comment]
تلاش کردم موردی رو که کاملا به درستی اشاره فرمودی عزیز جان در گلیف ها اصلاح کنم. البته با حالت ایده آل فاصله زیادی داره.

![screenshot from 2016-03-24 21-47-09](https://cloud.githubusercontent.com/assets/3116038/14025179/629a831e-f20a-11e5-8ccc-1b4a2a21078b.png)

**Comment by aziz** [comment]
فعلا می‌بندیم تا به صورت موردی بعدا ایشو ایجاد بشه
