### ISSUE TITLE
نام فونت در وزن لایت

### ISSUE THREAD

**Issue by alternatiph** [rastikerdar/shabnam-font#50]
سلام
به نظر میرسه اسم فونت توی وزن لایت مشکل داره

<img width="649" alt="screen shot 2018-10-14 at 12 35 04 pm" src="https://user-images.githubusercontent.com/11921744/46914691-a20f3e80-cfad-11e8-9cb3-f730416e8ca2.png">

**Comment by rastikerdar** [comment]
سلام
شاید اگر کل فایل‌های شبنم رو (به همراه کش) پاک کنید و آخرین ورژن رو دوباره نصب کنید ایراد برطرف بشه. چون روی سیستم خودم این مشکل وجود نداره و همه رو یک خانواده حساب می‌کنه.

**Comment by alternatiph** [comment]
مرسی با پاک کردن کش و فونت‌ها و نصب دوباره اوکی شد.
