### ISSUE TITLE
ایراد در اطلاعات متا در فونت بولد

### ISSUE THREAD

**Issue by dehghani-mehdi** [rastikerdar/shabnam-font#57]
سلام

تشکر بابت اینکه به صورت فعال فونت ها رو بروز می کنید.

در ورژن بولد، مقدار نام فونت
Font Name
برابر با
Shabnam
هست (همانند وزن عادی) که به نظر باید
Shabnam Bold
باشه.

سپاس

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای ایشو. اگر فونت‌های معروف لاتین رو هم ملاحظه بفرمایید همین روش فعلی رو دنبال کرده‌اند. وقتی مقدار رو به اون حالتی که میگید تغییر میدم دیگه مثلا توی لیبره‌آفیس اون رو از یک خانواده نمیشناسه و اسمش رو جداگانه توی لیست فونت‌ها میاره. در برنامه‌های دیگر نیز به همین صورت.

**Comment by dehghani-mehdi** [comment]
حرف شما صحیح هست.

در حال حاضر در برنامه ورد در لیست فونت ها به ازای هر وزن یک ایتم جداگانه در نظر گرفته شده به جز وزن بولد. برای استفاده از وزن بولد فونت باید فونت نوشته روی وزن عادی تنظیم و حالت بولد نرم افزار ورد فعال بشه؟ در این حالت از نسخه بولد فونت استفاده میشه؟

**Comment by rastikerdar** [comment]
بلی همینطوره. اگر هم‌نام نباشند وقتی روی دکمه بولد میزنید به جای استفاده از نسخه بولد فونت، خودش اقدام به ضخیم کردنش میکنه که خروجیش نامطلوبه.

**Comment by dehghani-mehdi** [comment]
ممنونم بابت پاسخ.

به امید دیدن نسخه سنگین فونت شبنم
