### ISSUE TITLE
مشکل اعداد فارسی

### ISSUE THREAD

**Issue by mehrdad517** [rastikerdar/shabnam-font#59]
با اعداد فارسی مشکل داره؟من همه فونت هاشو امتحان کردم فارسی نشد.

**Comment by rastikerdar** [comment]
توی بسته فونت پوشه‌ای قرار داره با نام:
Farsi-Digits
اگر از اون پوشه نصب کنید، توی برنامه‌ها فونت جدیدی به این اسم می‌بینید:
Shabnam FD

**Comment by mehrdad517** [comment]
تا زمانی که یه فایل استایل درست نکردم توی پوشه 
farsi-digits
درست نشد.
در کل خسته نباشید.
