### ISSUE TITLE
گلیف‌های ه باید بهتر شوند

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#6]
![screen shot 2015-12-02 at 2 22 24 am](https://cloud.githubusercontent.com/assets/3202/11521702/3586fc7c-98af-11e5-8db7-f0343e92728d.png)
![screen shot 2015-12-02 at 2 22 47 am](https://cloud.githubusercontent.com/assets/3202/11521703/3782e7a2-98af-11e5-808c-973dcdbb9197.png)
![screen shot 2015-12-02 at 2 23 59 am](https://cloud.githubusercontent.com/assets/3202/11521711/442297a0-98af-11e5-9440-8d64c8a4847c.png)

**Comment by rastikerdar** [comment]
یعنی شکلشون عوض بشه یا توی اندازه قطر و ...؟

**Comment by msm1365** [comment]
از اونجا که شبنم نسخ و نستعلیق نیست و تحریر هست اگر به ه نسخه دقت کنید باید ه کمی ارتفاع داشته باشد
شبیه صمیم تقریبا
بعد شکم ه فکر میکنم در خط تحریر باید بسته باشه

**Comment by rastikerdar** [comment]
@msm1365 
اینجوری منظورتونه؟
![screenshot from 2015-12-27 04-18-47](https://cloud.githubusercontent.com/assets/3116038/12008446/0a1ff43e-ac51-11e5-985b-593eee8c8dd7.png)


هر سه تا هـ ه ـه باید یه فکر اساسی براشون بشه.

**Comment by rastikerdar** [comment]
یا
![screenshot from 2015-12-27 04-24-38](https://cloud.githubusercontent.com/assets/3116038/12008454/eb531fee-ac51-11e5-97e1-20a91c6f53cf.png)

**Comment by rastikerdar** [comment]
یا
![screenshot from 2015-12-27 04-30-07](https://cloud.githubusercontent.com/assets/3116038/12008464/91f8ca7e-ac52-11e5-8a30-96b3a6dadc2d.png)

**Comment by rastikerdar** [comment]
این هـ چطوره؟
![screenshot from 2015-12-27 04-57-21](https://cloud.githubusercontent.com/assets/3116038/12008527/691ac6f8-ac56-11e5-96c3-025d1c490576.png)

**Comment by rastikerdar** [comment]
این حالت هایی هست که به ذهنم میرسه
![screenshot from 2015-12-27 05-02-48](https://cloud.githubusercontent.com/assets/3116038/12008539/28183fea-ac57-11e5-87bb-f8826209cc36.png)

**Comment by rastikerdar** [comment]
یکان اصلی اینه: شاید بهتر باشه
![screenshot from 2015-12-27 05-08-19](https://cloud.githubusercontent.com/assets/3116038/12008549/03e71e06-ac58-11e5-9a78-a4b4c9c36beb.png)

**Comment by msm1365** [comment]
بسته بودنش که درسته ولی اینکه صاف باشه یا مثل یکان کج باید توی جمله مشخص بشه. هر چند اگر شبیه یکان باشه نمیدونم درست هست یا نه.

**Comment by rastikerdar** [comment]
یه صفحه آزمایشی درست می کنم تا بشه با ورژن های مختلف  بررسی کرد. البته اگر راه بهتری و آسونتری برای بررسی به ذهنتون میرسه بگید.

**Comment by rastikerdar** [comment]
دارم روی قلم شبنم کار می کنم. اصلاحات و تغییرات اساسی دادم تا یه فونت خوب بشه. یه مقداری زمان می بره تا نسخه معمولی و ضخیمش آماده بشه.

**Comment by rastikerdar** [comment]
بالاخره دوستان فونت شبنم هم فکر می کنم با ورژن 0.6 به ریل خوبی افتاد.
کل سایز فونت تغییر کرد.
نسخه ضخیم به اندازه صحیحش رسید.
با زبان لاتین کامل هماهنگ شد.
بسیاری گلیف ها باز طراحی شد.
اصلاحات بسیاری روی اندازه و ضخامت ها انجام شد.
فقط مشکل اعراب فرصت نکردم.

داغون شدم!

**Comment by aziz** [comment]
خسته نباشی، واقعا تغییرات عالی بوده. یک قلم درجه یک داره میشه این شبنم.

**Comment by rastikerdar** [comment]
نسخه 0.7
![screenshot from 2016-01-01 02-11-15](https://cloud.githubusercontent.com/assets/3116038/12068868/ff7acc86-b02c-11e5-90d7-085b10f590fa.png)

**Comment by msm1365** [comment]
شبنم داره به فونت خوبی تبدیل میشه، خسته نباشید

**Comment by rastikerdar** [comment]
آخرین شکل ه این شده:
![screenshot from 2016-03-24 21-20-47](https://cloud.githubusercontent.com/assets/3116038/14024368/5f785e62-f206-11e5-82be-fcc635ad987e.png)

با اجازه ایشو رو می بندم ولی اگر فکر می کنید هنوز جای کار داره یا نمی پسندین لطفا ایشو رو دوباره باز کنید یا یک ایشو جدید ایجاد کنید تا بیشتر بهش بپردازم.

باز هم ممنون
