### ISSUE TITLE
چرا پروژه متوقف شده؟

### ISSUE THREAD

**Issue by mimsadAlef** [rastikerdar/shabnam-font#68]
سلام چرا پروژه متوقف شده به نظر من شبنم از بقیه فونتاتون قشنگ تره به آدم احساس مدرن بودن دست میده و خواندن مطالب هم راحت تره خواهش می کنم از این نظرتون صرف نظر کنید

**Comment by chromer030** [comment]
منم کاملا با نظر میم صاد موافقم ، فونت شبنم واقعا زیبا و مدرن و خواناست ، از این گذشته جز پراستفاده ترین فونت های وب هم هست ، امیدوارم توسعه اش ادامه پیدا کنه.

![1](https://user-images.githubusercontent.com/13361552/118590019-1ecfae00-b791-11eb-8b0f-f98d8152cadc.jpg)

**Comment by rastikerdar** [comment]
سلام
نه تنها شبنم که سایر فونت‌های آزاد هم کمابیش متوقف شده‌اند. توسعه این فونت‌ها با آمدن فونت‌های فراوان تجاری خوب در این چند سال (رفع کمبود فونت فارسی) و همچنین بدون حمایت مالی چندان منطقی به نظر نمیرسه و شاید همان ابتدا نیز باید متوقف می‌شد. به هر حال یک تجربه‌ یا خاطره‌ای شدند در قلمرو فونت فارسی.

توسعه شبنم برای همگان آزاد است و دیگران می‌تونند بر مبنای آن فونت دلخواه خودشون رو بسازند و نشر دهند.

**Comment by hamidpeywasti** [comment]
سلام
فونت شبنم، فونت خیلی خوبی است و در دو تا از پروژه‌ها از آن  استفاده کرده‌ام. کاش به این فونت به دید تجاری نگاه شود و لایسنس نسخه‌های جدید فروخته شود (مثلا فونت‌های خانواده‌ی ایران). من شخصا حاضر به خرید لایسنس تجاری این فونت هستم (همان‌طور که دیگر فونت‌ها را می‌خرم).
پیشنهاد: پروژه‌ی فونت شبنم تجاری شود.

**Comment by rastikerdar** [comment]
پروژه شبنم برای همیشه متوقف شده. من تلاشم رو کردم. شاید نسل های بعدی ادامه بدهند یا بهترش رو بسازند. اگر کسی مایل باشه می‌تونه تجاری ادامه‌اش بده. هیچ منعی وجود نداره.

اگر شبنم نیازتون رو برآورده می‌کنه ازش استفاده کنید، در غیر اینصورت پیشنهاد می‌کنم یه فونت تجاری در همین سبک بخرید.
