### ISSUE TITLE
مشکل همیشگی قلم‌های فارسی «کرنینگ رزژو» اینجا هم هست

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#8]
<img width="100" alt="screen shot 2015-12-02 at 4 49 51 am" src="https://cloud.githubusercontent.com/assets/3202/11521780/28d6aa3a-98b0-11e5-966b-251d9cd8cbd2.png">
<img width="179" alt="screen shot 2015-12-02 at 4 49 17 am" src="https://cloud.githubusercontent.com/assets/3202/11521781/2a84a1ca-98b0-11e5-8b1f-bcdc5f474933.png">
<img width="105" alt="screen shot 2015-12-02 at 4 49 04 am" src="https://cloud.githubusercontent.com/assets/3202/11521783/2cd5b356-98b0-11e5-80df-ec376a2151b7.png">

**Comment by aziz** [comment]
کرنینگ‌ها تو ورژن جدید خیلی عالی شده. مقایسه کنید گندی که یکان زده در کلمه زیر رو با شبنم جدید
<img width="53" alt="screen shot 2015-12-31 at 1 16 14 pm" src="https://cloud.githubusercontent.com/assets/3202/12064332/b986f93c-afc0-11e5-94ab-65cf64ac8c5e.png">
<img width="55" alt="screen shot 2015-12-31 at 1 16 22 pm" src="https://cloud.githubusercontent.com/assets/3202/12064334/bc61310e-afc0-11e5-81de-77cac5f2230b.png">

**Comment by rastikerdar** [comment]
سعی کردم تمامشو اصلاح کنم.
فقط ر و یـ به خاطر نقطه ها نمی شه کاریش کرد مگر جابجایی نقطه ها که مصیبتیست بس عظیم!
به هر حال اگر نیازی دیدین ایشو رو باز می کنیم.
![screenshot from 2016-01-01 02-05-56](https://cloud.githubusercontent.com/assets/3116038/12068851/7a0a2b1e-b02c-11e5-92a0-c74033640abe.png)
