### ISSUE TITLE
عدم تراز درست ع و غ و خ و ح و چ

### ISSUE THREAD

**Issue by aziz** [rastikerdar/shabnam-font#9]
![screen shot 2015-12-02 at 2 29 53 am](https://cloud.githubusercontent.com/assets/3202/11521801/59e099c4-98b0-11e5-94f1-347c09e3566c.png)
![screen shot 2015-12-02 at 2 30 02 am](https://cloud.githubusercontent.com/assets/3202/11521803/5b2bbe58-98b0-11e5-9193-cfcf0e8a4010.png)

**Comment by rastikerdar** [comment]
بهتر شد؟
![ain-hah](https://cloud.githubusercontent.com/assets/3116038/11548292/fd340614-996f-11e5-9827-b3c528f97739.png)

**Comment by rastikerdar** [comment]
البته به نظر من شکل ح و ـح اصلا جالب نیست. نیاز به یک باز طراحی حسابی دارند.

**Comment by zoghal** [comment]
یکی از موارد سخت طراحی حروف همین قوس  منفی هست.  واقعا هم سخته :(

**Comment by rastikerdar** [comment]
@zoghal 
 وای نگید کابوس من همین قوس هاست. خیلی وحشتناکند. بدترینش همین ح

**Comment by zoghal** [comment]
@rastikerdar از اونجایی که قبلا یکان رو در ۹ وزن گسترش دادم. تو یککان وحشتناک هست. چاره ای نیست که متریکش رو کمی تغییر داد تا  بشود به یک قوس مورد پسند دست پیدا کرد.
یکان بر اساس خط بنایی(کاشیکاری) پیاده سازی شده و نمیشه زیاد انتظار بیشتر داشت.

**Comment by rastikerdar** [comment]
موافقم.
البته یکان یا این شبنم علی‌رغم ظاهر سادش به نظر عجیب و خاص هست.
من به شخصه تو این چند مورد، اندازه و شکل قوس ـع رو بیشتر می پسندم.
این شبنم خیلی کار داره. تمام ایشو هایی که عزیز جان گذاشته درسته و باید کار بشه.
واقعا آدم کم میاره! :(
امیدوارم بتونیم به یه جای خوبی برسونیمش

**Comment by zoghal** [comment]
@rastikerdar تازه اول کاری آقای رستگار عزیز، نگو کم میاری که از آینده خبر نداری.
بزرگترین مشکل تو کار طراحی فونت همین مدیریت توسعه فونت هست. یعنی خیلی همت کنیم بتونیم یک فونت یا چندتای محدود رو روش کار کنیم. 
دقیقا از همینجا برای من شروع شد دیدم اگر بخوام درگیر اصلاح سازی فقط بشم یک عمر زمان میبره آخرش میشه چندتا فونت. سر همین موضوع رفتم تو کار تجزیه و تحلیل حروف ببینم راهی داره اون رو مکانیزه کنم.
و این هم نتیجه و آنچه قولش رو داده بودم.
ببینید دموی تست زنده فونت رو:
https://www.youtube.com/watch?v=6XdjHYIWgJ0

فقط کافیه حروف در قالب svg در یک فولدر قرار داده شود. سایر کارها اتوماتیک انجام میشه. برای حروف هم یک گرید وجود داره که به عنوان تمپلیت استفاده میشه.
cc @aziz

**Comment by rastikerdar** [comment]
من سعی می کنم به تدریج فونت ها رو اصلاح کنم اما خب دیگه اون وقت و سرعت و انگیزه قبل رو ندارم. انشاءا.. روزی جامعه ایرانی به ویژه دوستان علاقه‌مند به نرم‌افزار آزاد به این نتیجه برسند که با حلوا حلوا گفتن دهن شیرین نمیشه و باید به طور جدی وارد معرکه بشند. شاید هم من مسیر رو کاملا اشتباه رفته ام. بگذریم.

برنامه جالبی به نظر میرسه آقا صالح. فراموش نکنی که یک راهنمای خوب هم براش بنویسی.

**Comment by zoghal** [comment]
اااا نشد که، باید بدونید که خط، خوشنویسی ،حروف، قلم آنقدر  حرمت بالایی دارد که خداوند به آن سوگند یاد کرده. 
حتی روایت هست :دی که کسی به خط وارد شود کم بیارد و خارج شود یکی از گناهان کبیره را انجام داده. :)))

دم از جامعه زدی، کلا کارش خیلی درسته فقط شعار و انتظار، تا کارشون راه میوفته سریع فراموشت می‌کنند. اما همه اینطوری نیستند. توی همین جامعه افرادی هستند که باور کردنی نیستند. فقط یک کمی تنبل تشریف دارند. 
یک حدسی که میزنم این هست که انتظار داشتید با اعلام شماره حساب، حداقل امکان کمی حمایتی مالی ازتون بشه، اما در نتیجه هیچ عکس العملی رو شاهد نبودید. تجربه ای که خودم کردم این بود که تا زمانی مثل pfont.ir عمل نکنید یعنی عکس افراد رو نمایش ندی هیچ کمکی انجام نمیشه. یا آنقدر راه حمایت رو ساده نکنی کسی زخمت به خودش نمیده بره حساب به حساب انتقال وجه انجام بده.
اگر درست حدس زدم پیشنهاد میکنم راه حمایت رو آسون کنید. حمایت میشید.

در مورد مسیر هم باید بگویم هم بله هم نه، این کار کمی فرسایشی هست. مخصوصا اگر اصولی و بدون دانش مورد نیاز انجام بشه شدیدا گنگ و پیچیده میشه.
اشتباه نرفتید چون اصلا راه و روش مسخصی تا به امروز وجود نداشته که بخواهید راه درست رو برید. این نکته ای بود که من ۲ سال پیش بهش رسیدم و سعی کردم راه و مسیر درست رو مشخص کنم. و فکر میکنم تا ۷۰٪ موفق شدم. حداقل مسایل پایه رو که کاملا اطمینان دارم.

واقعیتش وقتی خودم رو با شما مقایسه میکنم(البته اون زمان که شروع کردم) میبینم شما ۶۰ برابر نسبت به من بهترید. حداقل بدون دانش طراحی حروف تا اینجا پیش بردید. و این نشان از استعداد و توانایی بالای شما داره.
پیشنهاد میکنم هماهنگ  یک گپی صوتی باهام داشته باشیم. در کل سرد نشید بهار نزدیک است.

**Comment by rastikerdar** [comment]
آقا صالح عزیز منظور من این بود که این فونت ها با تلاش بسیار ساخته شدند. و اگر دوستان دلشون می خواد در هر حوزه ای محصول آزاد داشته باشند باید همت کنند. تلاش کنند. چه فردی چه گروهی.

ضمنا آقا صالح من هیچ کجا از حمایت مالی سخن نگفتم. تا الان هیچ درخواست مالی هم نداده ام. توی وبلاگ هم گفتم اگر کسی دلش می خواد هدیه کنه واریز کنه. واقعیتش اصلا بنا بر اعلام شماره حساب نبود. چه حال چه آینده. فراموش هم کرده بودم تا الان که فرمودید. ممنونم که اشاره کردید. شماره رو بر می دارم تا شبهه‌ای نماند. این فقط به دلیل درخواست هایی که به صورت خصوصی و عمومی برای من آمد اعلام شد. احساس کردم بی احترامیه اگر انجام ندم. گفتم شاید برخی دلشون می خواد اینگونه مشارکت کنند. حال آنکه همه جا توی ایمیل ها و پاسخ ها و ... گفتم تنها درخواست من مشارکت در توسعه به صورت پیشنهاد، تغییر، اصلاح گزارش و انتقاد و ... است و نه حمایت مالی. البته این رو هم اشاره کنم که خوشبختانه چیزی هم واریز نشده. اینطوری مسئولیتی هم از این بابت گردن من نیست و نخواهد بود.

در مورد فرسایشی بودن راه قبول بفرمایید که مسیر هر چقدر هم سخت و ناهموار باشه با همراهی و کار گروهی سهل میشه. من که متوقف نشدم. تا اونجایی که توان داشته باشم تلاش می کنم در کنار کار اصلی ام به جامعه نیز کمک کنم.

موید باشید.

**Comment by zoghal** [comment]
ای کاش این حرف شما رو یک عده می شنیدند!!!:(

در مورد حمایت مالی گفتم حدس میزنم اینطوری باشه. نقل قول از طرف شما نبود. به حر حال زحمات شما ستودنی است. کسی نمیتونه منکرش بشه. و از یک طرف بحث مباحث مالی هم غیر قابل انکار هست. مخصوصا در این دوره زمانه.
نمی دانم چرا فکر میکنید گرفتن حمایت مالی براتان مسیولیت ایجاد می‌کند. اما اگر دنبال مشارکت هستید باید بدونید که خیلی ها دوست دارند تو این پروژه به نوعی کمک و مشارکت داشته باشند اما چون نه توانایی یا وقتش لازم رو ندارند، می‌تونند با کمک مالی این مشارکت رو انجام بدند.
من شخصا که دارم از همین کمک‌های مالی اموراتم رو میگذرونم. کم هست اما لذت بخش و مسیولیتی رودوشم نیست چون خودشون با خواسته خودشون اینکار رو می کنند.


اوووو خیلی هم خوب این خبر رو شنیدم. پس هنوز خسته نشدید. عالی بود این خبرت.

**Comment by rastikerdar** [comment]
هممم آقا صالح قبلا با دوستان در مورد دونیشن صحبتی داشتیم گفتند که مشکلی ایجاد نمی کند. اما از یه چیزی خیلی واهمه دارم. اگر من بنا به هر دلیلی دیگه فونت ها رو توسعه ندادم هر چند که کلا آزاد هستند برای مثال اگر مُردم، حقی گردن من نیست؟

**Comment by zoghal** [comment]
دونیشن یک نوع همیاری و مساعدت هست. پروژه های آزاد همیشه ریسک سوخت شدند رو همراه دارند. کسی که دونیشن انجام میده فکر می‌کنم به این سطح فکری رسیده باشه که داره چه نوع کمکی میکنه. دونیشن بیشتر تشویقی ایست برای ادامه و حرکت به جلو ، پس هیچ حقی گردن شما نخواهد بود.(نظر شخصی من هست.)

**Comment by rastikerdar** [comment]
فکر می کنم به قوس خوبی رسیدم. توی ورژن 0.6 گذاشتم
![screenshot from 2015-12-31 11-26-45](https://cloud.githubusercontent.com/assets/3116038/12062419/82555f12-afb1-11e5-8b9e-bf2294d8dc66.png)

**Comment by zoghal** [comment]
:+1: 
جای بهتر شدن هم داره. تصویر زیر رو ببینید. 
این قوس از دو حرکت قلم تشکیل میشه.
پس می تونه  جای بازی بیشتری داشته باشه.
البته این فونت چون منولاین هست. همین هم عالیه.
![dsc01216](https://cloud.githubusercontent.com/assets/174688/12064625/14e5b8f6-afdd-11e5-860d-a683da726af9.jpg)

**Comment by rastikerdar** [comment]
مرسی صالح جان. این باید تو پرستو به کارش بگیرم.
